config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :memberships
  resources :users
  resource :session, only: [:new, :create, :destroy]
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'
  
  root 'breweries#index'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { less_than_or_equal_to: Proc.new { Time.now.year } }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

 def self.top(n)
   sorted_by_rating_average = Brewery.all.sort_by{ |b| -(b.average_rating || 0) }
    sorted_by_rating_average[0, n]
   
   
   # miten? ks. http://www.ruby-doc.org/core-2.1.0/Array.html
 end


 def to_s
  "#{name}"
end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @top_breweries = Brewery.top 3
  end
 def index
    @breweries = Brewery.all
    @top_breweries = Brewery.top 3

    order = params[:order] || 'name'

    @breweries = case order
      when 'name' then @breweries.sort_by{ |b| b.name }
      when 'year' then @breweries.sort_by{ |b| b.year }
    end
end
 def list
end

  

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragment('brewerylist')
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragment('brewerylist')
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_fragment('brewerylist')
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breweries</h1>
<p> Number of breweries: <%= @breweries.count %> </p>
<% cache 'brewerylist', skip_digest: true do %>
<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', breweries_path(order:"name") %> </th>
      <th> <%= link_to 'Year', breweries_path(order:"year") %> </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>

        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Brewery', new_brewery_path, class:'btn btn-primary' %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Year</a> </th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>
<% cache @brewery do %>
<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
</p>

<p>
  <i>Established in </i>
  <i><%= @brewery.year %></i>
</p>

<p>
  <italic>Number of beers: </italic>
  <%= @brewery.beers.count %>
</p>

<p>
 <% @brewery.beers.each do |beer| %>
   <%= link_to beer.name, beer %>
 <% end %>
</p>
<% end %>
<p>
  <%= link_to 'list of beers', beers_path  %>
</p>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>